name: tests

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
        env: [base]
        pytest_folder: [tests]
        pytest_ignore: [""]
        include:
        - os: macos-latest
          python-version: 3.9
          env: base

        - os: windows-latest
          python-version: 3.9
          env: base

        - os: ubuntu-latest
          python-version: 3.9
          env: torch
          pytest_folder: tests/test_tensor

        - os: ubuntu-latest
          python-version: 3.9
          env: jax
          pytest_folder: tests/test_tensor

        - os: ubuntu-latest
          python-version: 3.9
          env: tensorflow
          pytest_folder: tests/test_tensor

        - os: ubuntu-latest
          python-version: 3.9
          env: slepc
          pytest_ignore: "tests/test_tensor"

    steps:
    - uses: actions/checkout@v3

    - name: Install micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ci/requirements/py-${{ matrix.env }}.yml
        environment-name: test-env
        extra-specs: python=${{ matrix.python-version }}
        cache-env: true

    - name: Test all with pytest
      run: pytest ${{ matrix.pytest_folder }} --cov=quimb --cov-report=xml --ignore=${{ matrix.pytest_ignore }}

    - name: Report to codecov
      uses: codecov/codecov-action@v3
